CHANGELOG.md, package-lock.json, package.json
Related to camunda/camunda-modeler#2334
=> deps: update element-templates-json-schema to 0.4.0

CHANGELOG.md, package-lock.json, package.json
=> prepare release

package-lock.json, package.json, test/fixtures/rest-connector-broken.json, test/fixtures/rest-connector.json, test/spec/validationSpec.js
related to https://github.com/bpmn-io/bpmn-js-properties-panel/pull/602
=> Add feel validation

CHANGELOG.md, package-lock.json, package.json, test/fixtures/rest-connector-broken.json, test/fixtures/rest-connector.json, test/fixtures/rpa-broken.json, test/fixtures/rpa.json, test/spec/validationSpec.js
- bump schema version
- verify that `elementType` is validated
- prepare release
=> deps: bump element template version

package-lock.json, package.json, test/fixtures/rest-connector-broken.json, test/fixtures/rest-connector.json, test/spec/validationSpec.js
=> deps: bump to `@camunda/zeebe-element-templates-json-schema@0.4.0`

package-lock.json, package.json
=> deps: bump schema version

CHANGELOG.md, package-lock.json, package.json, test/fixtures/rest-connector-broken.json, test/fixtures/rest-connector.json, test/spec/validationSpec.js
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/731.
=> deps: bump to`@camunda/zeebe-element-templates-json-schema@0.5.0`

CHANGELOG.md, package-lock.json, package.json
=> deps: bump to`@camunda/element-templates-json-schema@0.10.1`

CHANGELOG.md, package-lock.json, package.json, test/fixtures/multiple-connectors-errors.json
related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/840
=> Allow optional taskheader

CHANGELOG.md, package-lock.json, package.json
In the context of implementing support for multiple conditions https://github.com/camunda/element-templates-json-schema/issues/91, https://github.com/bpmn-io/bpmn-js-properties-panel/issues/817
=> Update deps 

CHANGELOG.md, package-lock.json, package.json, test/fixtures/message.json, test/spec/validationSpec.js
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/890
=> feat: support message properties

CHANGELOG.md, package-lock.json, package.json, test/fixtures/rest-connector-broken.json, test/fixtures/rest-connector.json, test/spec/validationSpec.js
=> Support tooltips

CHANGELOG.md, package-lock.json, package.json, test/.eslintrc, test/distro/distroSpec.cjs, test/spec/validationSpec.js
In this PR, I'd like to split the changelog into the sections for C7 and C8. IMO this makes it easier to comprehend.
=> Update json schemas & update changelog

package-lock.json, package.json, test/fixtures/multiple-connectors.json
Related to https://github.com/camunda/camunda-modeler/issues/2936
Requires https://github.com/camunda/element-templates-json-schema/pull/117 to be merged, release, and integrated.
=> deps: update to `@camunda/zeebe-element-templates-json-schema@0.14.0`

CHANGELOG.md, package-lock.json, package.json, test/fixtures/message-broken.json, test/fixtures/message.json, test/spec/validationSpec.js
Related to https://github.com/camunda/camunda-modeler/issues/3573
=> feat: support receive and send task templating

package-lock.json, package.json, test/fixtures/multiple-connectors-errors.json, test/fixtures/multiple-connectors.json
related to https://github.com/bpmn-io/bpmn-js-element-templates/issues/19
=> feat: support isActive

CHANGELOG.md, package-lock.json, package.json, renovate.json, test/fixtures/rest-connector.json, test/spec/validationSpec.js
=> deps: update to @camunda/zeebe-element-templates-json-schema@0.19.0

.github/workflows/CI.yml, package-lock.json, package.json, tasks/createStandaloneValidator.js, test/spec/validationSpec.js
Superceedes https://github.com/bpmn-io/element-templates-validator/pull/38.
=> Housekeeping

CHANGELOG.md, package-lock.json, package.json, test/fixtures/linked-resource-broken.json, test/fixtures/linked-resource.json, test/spec/validationSpec.js
Updates the template schema to newest version and adds tests for linkedResource.
related to https://github.com/bpmn-io/bpmn-js-element-templates/issues/137
To ensure you provided everything we need to look at your PR:
=> deps: update to @camunda/zeebe-element-templates-json-schema@0.22.0

CHANGELOG.md, package-lock.json, package.json
* follow-up to https://github.com/bpmn-io/element-templates-validator/pull/49
To ensure you provided everything we need to look at your PR:
=> Update `@camunda/zeebe-element-templates-json-schema` to v0.22.2

package-lock.json, package.json, test/fixtures/called-decision-broken.json, test/fixtures/called-decision.json, test/fixtures/called-element-broken.json, test/fixtures/called-element.json, test/fixtures/form-definition-broken.json, test/fixtures/form-definition.json, test/fixtures/linked-resource-broken.json, test/fixtures/linked-resource.json, test/spec/validationSpec.js
related to https://github.com/camunda/camunda-modeler/issues/5027
To ensure you provided everything we need to look at your PR:
=> test: add tests for `bindingType`

CHANGELOG.md, package-lock.json, package.json, test/fixtures/priority-definition-broken.json, test/fixtures/priority-definition.json, test/spec/validationSpec.js
Adds test to cover zeebe:priorityDefinition and bumps schema version.
Related to https://github.com/camunda/camunda-modeler/issues/5092
To ensure you provided everything we need to look at your PR:
=> test: add `zeebe:priorityDefinition` tests
